version: "2"
services:
  nginx:
    image: nginx:alpine
    ports: 
      - "3080:80"
      - "3443:443"
    volumes:
      - ./etc/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - containers-network
  quirosystem:
    image: node:alpine
    ports: 
      - "3456:3000"
    volumes:
      - .:/app
    working_dir: /app
    networks: 
      - containers-network
    entrypoint: ["npm", "start"]
networks: 
  containers-network:
    driver: bridge
